source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Spurious_Example', :exclusive => true do
  pod "Spurious", :path => "../"
end

target 'Spurious_Tests', :exclusive => true do
  pod "Spurious", :path => "../"

  pod 'Quick', '~> 0.5.0'
  pod 'Nimble', '2.0.0-rc.2'
end
